sellsei_ecommerce_core_index:
    path:     /
    defaults: { _controller: SellseiEcommerceCoreBundle:Default:index }
    options:
        expose: true

sellsei_ecommerce_core_homepage:
    path:     /home
    defaults: { _controller: SellseiEcommerceCoreBundle:Default:home }
    options:
        expose: true